# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
  else
    config.vm.synced_folder ".", "/vagrant"
  end
  #config.vbguest.auto_update = false
  config.vm.define "node1" do |node1|
    node1.vm.box = "bento/centos-7.7"
    node1.vm.hostname = 'node1'
    node1.vm.network :private_network, ip: '10.33.3.114'
    node1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--name", "omnidb_pglogical_node1"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end
  config.vm.define "node2" do |node2|
    node2.vm.box = "bento/centos-7.7"
    node2.vm.hostname = 'node2'
    node2.vm.network :private_network, ip: '10.33.3.115'
    node2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--name", "omnidb_pglogical_node2"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end
  config.vm.provision :shell, :path => "bootstrap.sh"
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
    config.vbguest.no_install = true
    config.vbguest.no_remote = true
  end
end
