# Default login username: "admin" and password "admin".
version: '3.7'
services: 
  omnidb:
    container_name: omnidb
    image: robert0714/omnidb:v2.16.0-alpine_3.10.3
    privileged: true
    user: root
    volumes:
    - $PWD/omnidb_data:/etc/omnidb:Z 
    environment:
    - TZ=Asia/Taipei
    ports: 
     - "25482:25482" 
     - "8080:8080" 
